using HarmonyLib;
using RimWorld;
using Verse;

namespace CarpenterTable;

[HarmonyPatch(typeof(RecipeDef), nameof(RecipeDef.WorkAmountForStuff))]
public static class RecipeDef_WorkAmountForStuff
{
    public static void Postfix(RecipeDef __instance, ThingDef stuff, ref float __result)
    {
        // If the RecipeDef was generated by the StaticConstructorClass
        if (__instance.defName.Contains(StaticConstructorClass.GeneratedRecipeDefPrefix))
        {
            // Work amount is the product's WorkToBuild dependent on the stuff
            __result = __instance.ProducedThingDef.GetStatValueAbstract(StatDefOf.WorkToBuild, stuff);
        }
    }
}