using HarmonyLib;
using Verse;

namespace CarpenterTable;

[HarmonyPatch(typeof(RecipeDef), nameof(RecipeDef.AvailableNow), MethodType.Getter)]
public static class RecipeDef_AvailableNow_Getter
{
    public static void Postfix(RecipeDef __instance, ref bool __result)
    {
        // If the RecipeDef would normally be available and was generated by the StaticConstructorClass
        if (__result && __instance.defName.Contains(StaticConstructorClass.GeneratedRecipeDefPrefix))
        {
            // Change the result to whether or not the resulting ThingDef's research requirements have been met
            __result = __instance.ProducedThingDef.IsResearchFinished;
        }
    }
}